### ISSUE TITLE
Release builds to the forge

### ISSUE THREAD

**Issue by ghoneycutt** [Ericsson/puppet-module-cgroups#9]
Hi @Phil-Friderici 

Could you release v1.0.0 of this module to the forge?

Once @crayfishx 's v2.0.0 gets merged, we can ask Puppet to approve this module and they will want to see that all tagged releases are on the Forge.

**Comment by crayfishx** [comment]
1.0.0 and 1.0.1 ;-)

**Comment by Phil-Friderici** [comment]
Will put them on the forge in one go after reviewing and merging v2.0.0, ok ?

**Comment by crayfishx** [comment]
I see you've merged 2.0.0 - woot! thanks for all the work and collaboration @Phil-Friderici and @ghoneycutt .... If we can get a forge release that would be awesome.

**Comment by Phil-Friderici** [comment]
working on that at the very moment :)

**Comment by Phil-Friderici** [comment]
feels a bit fishy to add metadata.json when it was not included in the original 1.0.0

**Comment by Phil-Friderici** [comment]
uploaded them https://forge.puppet.com/ericsson/cgroups
